steps:
  # Run tests and save to file
  - name: 'cgr.dev/chainguard/go:1.20'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        go test -timeout 1m -v ./...

  # Docker Build
  - name: 'cgr.dev/chainguard/ko:latest'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        ko build main
    env:
      - "KO_DOCKER_REPO=$LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME"

# Store images in Google Artifact Registry
images:
  - $LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME:$SHORT_SHA

substitutions:
  _REPO_NAME: sample-repo